GENERAL: 
    # Application type: 0 - min bar tracker
    #                   1 - min bar classifier - rf model
    #                   2 - min bar pair trader
    APPLICATION: 2

    # Log level: 0 - LOG_FATAL
    #            1 - LOG_ERROR
    #            2 - LOG_WARNING
    #            3 - LOG_INFO
    #            4 - LOG_VERBOSE
    #            5 - LOG_DEBUG
    LOG_LEVEL: 3

########################################################
#################### App configs #######################
########################################################
# ------------- MINBAR_PAIR_TRADER -----------------
MINBAR_PAIR_TRADER:
    PAIR_SYM_X: EURUSD
    PAIR_SYM_Y: USDCHF
    LR_LEN: 6000  # Linear regression history length
    THRESHOLD_STD: 0.1  # in unit of std

# ------------- MINBAR_TRACKER -------------------
MINBAR_TRACKER:
    HISTORY_BAR_FILE: EURUSD_labeled.csv
    PREDICTOR_TYPE: 0 #  0 - MA predictor

MA_PREDICTOR:
    MA_PREDICTOR_TYPE: 1 # 0 - MA Grad Hunter
                         # 1 - MA crosser
    MA_TYPE: LWMA

    MA_GRAD_HUNTER: 
        LOOKBACK: 90
        STARTOFF_SLOPE: 1.0e-6
        TURN_POINT_OFFSET: 10
    MA_CROSSER:
        LONG_LOOKBACK: 120
        SHORT_LOOKBACK: 10
        TURN_POINT_EXPIRY: 10
        STARTOFF_GAP: 5.e-5

