GENERAL: 
    # Application type: 0 - min bar tracker
    #                   1 - min bar classifier - rf model
    APPLICATION: 0

    # Log level: 0 - LOG_FATAL
    #            1 - LOG_ERROR
    #            2 - LOG_WARNING
    #            3 - LOG_INFO
    #            4 - LOG_VERBOSE
    #            5 - LOG_DEBUG
    LOG_LEVEL: 3

########################################################
#################### App configs #######################
########################################################
MINBAR_TRACKER:
    HISTORY_BAR_FILE: EURUSD_labeled.csv
    PREDICTOR_TYPE: 0 #  0 - MA predictor

MA_PREDICTOR:
    MA_PREDICTOR_TYPE: 0 # 0 - MA hunter
    MA_TYPE: LWMA

    MA_GRAD_HUNTER: 
        LOOKBACK: 90
