PREDICTION:
    BUY_FAST_PERIOD: 98
    BUY_SLOW_PERIOD: 830
    BUY_MODEL: eurusd_buy_profit_3920.pkl

    SELL_FAST_PERIOD: 46
    SELL_SLOW_PERIOD: 427
    SELL_MODEL: eurusd_sell_profit_1700.pkl
    
    SYMBOL: eurusd

    FEATURE_LIST: DMA,RSI,EMA
